Reed-CompBio/spras

- .github/workflows/test-spras.yml
- README.md
- environment.yml
Closes #30
I listed the new packages separately so that we can remove them later if we decide to Dockerize GraphSpace.
@annaritz do you know whether GraphSpace needs version 2.10.0 of the requests package specifically?  Only that version is allowed in https://github.com/adbharadwaj/graphspace-python/blob/42283556eb3a52212cfa9f75dfc694c70069add7/requirements.txt#L3.  That prevents us from installing it through conda.  It is so old it conflicts with other packages in our environment.  It may also be throwing warnings in our test code
```
test/OmicsIntegrator1/test_oi1.py::TestOmicsIntegrator1::test_oi1_required
/usr/share/miniconda3/envs/spras/lib/python3.8/site-packages/requests/models.py:170: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from …
```
> Add GraphSpace dependencies to conda environment

- docker-wrappers/PathLinker/Dockerfile
- docker-wrappers/PathLinker/README.md
- docker-wrappers/PathLinker/environment.yml
- docker-wrappers/PathLinker/pathlinker-files.txt
- src/pathlinker.py
The updated Dockerfile no longer uses conda to create the environment, which also eliminates the custom ENTRYPOINT.  I'm using the Alpine version of Python, which leads to smaller images.  Our current conda-based image is 303.53 MB.  This one is 21.61 MB.
Another change is that I'm downloading the `requirements.txt` from PathLinker's GitHub repository instead of tracking the required package versions here.  I have to remove the last line from the `requirements.txt` file because it isn't a valid Python package.
If the tests pass, I'll merge this and then sync it with #49.
> Switch PathLinker image to Alpine Python

- src/omicsintegrator1.py
Closes #60
This bug was introduced in #49.  Previously volumes were mapped such that `/OmicsIntegrator1` inside the container corresponded to the root of the `spras` repository on the local filesystem, which made it a suitable temporary directory for Omics Integrator 1.  That is no longer the case.
Now the temporary directory is set to the output directory for this Omics Integrator 1 run.  I was able to reproduce #60, and this change fixed it for me.
> Fix bug in Omics Integrator 1 TMPDIR

- .github/workflows/test-spras.yml
The version of "Singularity" that joined the Linux Foundation is known as Apptainer. This pull request migrates our GitHub Actions workflow to install Apptainer.
My expectation is that Apptainer currently uses symlinks so that we can continue running `singularity` commands: https://apptainer.org/docs/user/main/singularity_compatibility.html#singularity-command-symlink
> Migrate GitHub Actions to Apptainer

- .github/workflows/test-spras.yml
- docker-wrappers/AllPairs/Dockerfile
- docker-wrappers/AllPairs/README.md
- docker-wrappers/PathLinker/Dockerfile
- docker-wrappers/PathLinker/README.md
- spras/allpairs.py
- spras/pathlinker.py
This updates the PathLinker Docker image to include bash as described in https://github.com/Reed-CompBio/spras/issues/130#issuecomment-2182842994
Before making the change, I versioned the prior image as v1 and pushed it to DockerHub. This update is now v2.
> Add bash to PathLinker image

- .github/workflows/test-spras.yml
- docker-wrappers/SPRAS/Dockerfile
@ntalluri reports several failing CI tests caused by insufficient disk space in the GHA runner's host OS, and it looks like the available disk is being chewed through by the docker build tests.
This PR adds an additional step to each container build test that explicitly deletes the image after it has been built. Hopefully this leads to more efficient use of space.
> Modify GHA Docker build tests to clean up after themselves

- docker-wrappers/SPRAS/README.md
- docker-wrappers/SPRAS/example_config.yaml
- docker-wrappers/SPRAS/snakemake_long.py
- docker-wrappers/SPRAS/spras_profile/config.yaml
To avoid tying Snakemake execution to the current terminal (which is bad if
you ever want to log out of the AP or let your computer fall asleep), the new
script `snakemake_long.py` wraps Snakemake execution in an HTCondor local
universe job. This job is submitted like a regular HTCondor job, but it runs
on the AP in the context of the submit directory.
Usage:
`snakemake_long.py --snakefile (OPTIONAL) </path/to/snakefile> --profile (REQUIRED) </path/to/profile> --htcondor-jobdir (OPTIONAL) </path/to/logs>`
The only CLI option that might feel new here is `htcondor-jobdir`. This is
actually the same CLI used by the HTCondor executor, and it specifies a directory
in which logs are placed. I chose to keep names the same with this script so it
feels more familiar to Snakemake users.
> Enable long Snakemake workflows in HTCondor

- .github/workflows/release.yml
Now whenever a new tag of SPRAS is pushed to github, the corresponding container from that tag is build and pushed to Dockerhub.
> Add auto container release action

- .github/workflows/build-containers.yml
- .github/workflows/release.yml
Follow up on unsuccessful login in #200
> Test Docker login

- .readthedocs.yaml
After reading through @agitter's notes in the linked issue, I agree that the issue appears to be that RTD is using python 3.12 here. A downgrade to 3.11 should do the trick for now.
Closes #211
> Downgrade RTD python version to 3.11 to fix build error

- environment.yml
- pyproject.toml
We have seen the error
```
snakemake\dag.py:1612: RuntimeWarning: coroutine 'DAG.sanitize_local_storage_copies' was never awaited
self.sanitize_local_storage_copies()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
This was fixed in Snakemake pull request 2972 released in version 8.17.0.
```
https://github.com/snakemake/snakemake/pull/2972
https://github.com/snakemake/snakemake/pull/2960
```
> Fix Snakemake DAG.sanitize_local_storage_copies

- spras/allpairs.py
- spras/dataset.py
- spras/pathlinker.py
- spras/prm.py
- spras/runner.py
Adds global type-hints related to PRM, and corrects the NotImplementedError error handling inside PRM.
This also takes the chance to update "NODEID" calls to Dataset.NODEID.
> refactor: cleanup prm

- spras/dataset.py
- spras/evaluation.py
This is the same idea as `self.interactome` and is both unused and never set to anything past `None.
> refactor(dataset): drop unused edge_table parameter

- .gitignore
- config/config.yaml
- spras/containers.py
This is a follow-up to https://github.com/Reed-CompBio/spras/pull/145#issuecomment-1970044310, taking the neutral approach where GC is left up to the user, but in such a way where it is made convenient. This addresses the `allpairs` creating git-commitable artifacts on the cwd.
This path could be made a parameter in the encompassing `run_container_singularity` function, though that seems out of scope for SPRAS itself.
[The commit name is misleading - it should be `mv`, not `gc`.]
> fix(singularity): mv unpacked files

- spras/omicsintegrator1.py
See https://github.com/fraenkel-lab/OmicsIntegrator/blob/0a57ede6beeef6e63b86d19898e560d62015e85d/scripts/forest.py#L1348-L1353. Debugged by @AMINOexe. The attached GitHub link links to the commit we use in the OI1 Dockerfile: https://github.com/Reed-CompBio/spras/blob/326a5e6f7fbd9a77c8e42384595a658678530652/docker-wrappers/OmicsIntegrator1/Dockerfile#L12
[Incorrectly flagged as needed for benchmarking, turns out dummyMode as terminals works just fine for our purposes. This should still be fixed.]
Since OI1 is random, we unfortunately can not test for correctness.
> fix: supply correct oi1 flag

- Snakefile
Anyone is welcome to try to create a test case for this, but I've tested it by running this patch on spras-benchmarking several times over 16 cores: without the patch, Snakemake fails almost every single time. With this patch, it has never failed despite running this several times.
Closes #279. Closes #268.
> fix: multithreading error

- test/generate-inputs/test_generate_inputs.py
This catches the error that occurred in #223 earlier than after the docker container is ran.
> test: make sure all inputs exist

- docs/conf.py
(This takes you to https://github.com/Reed-CompBio/spras/blob/main/docs/usage.rst).
> docs: display "edit on github" links

- .github/workflows/test-spras.yml
- spras/omicsintegrator1.py
Fixes the `main` typo, and closes #351.
> ci: use pre-commit from conda

- Snakefile
`pathway.txt` is an interesting intermediary file, regardless of whether downstream analysis is enabled or not.
This rule change means that `pathway.txt` now gets recreated if it gets deleted.
> fix: preserve pathway.txt files

- .github/workflows/build-and-remove-template.yml
- .github/workflows/build-containers.yml
- docs/contributing/index.rst
Leftover from #8 that silently killed `build-and-remove-template.yml`. Also corrects the branch name in docs.
> ci: use main branch

- docker-wrappers/SPRAS/README.md
Inching towards #395, by mentioning setting `container_framework`. After #396, we can move this to RTD.
> docs(htcondor): mention container_framework

- .github/workflows/merge-conflicts.yml
Labels merge conflicts on open PRs. Frozen to a commit hash since this isn't an officially maintained GitHub action.
> ci: label merge conflicts

- config/egfr.yaml
- docker-wrappers/AllPairs/README.md
The readme incorrectly states the source is in the SPRAS repo
> docs(APSP): Link to current location of APSP source
